'use strict';

const fs = require('fs');
const path = require('path');

const { discoverLibrary } = require('./discovery');
const { atomicWrite, listSkillFiles } = require('./util');

const GENERATED_MARKER = '<!-- Generated by ash control plane. Do not edit by hand. -->';

function tableText(value, limit) {
  const maximum = limit || 180;
  const compact = String(value || '').split(/\s+/).filter(Boolean).join(' ').replace(/\|/g, '\\|');
  return compact.length > maximum ? compact.slice(0, maximum - 1).trim() + '…' : compact;
}

function generateCatalog(settings, selectedSkills) {
  const skills = selectedSkills || discoverLibrary(settings);
  const lines = [
    '# ASH Skill Catalog',
    '',
    GENERATED_MARKER,
    '',
    'Generated by `ash catalog --write` or `ash repair --apply`.',
    '',
    '| Skill | Library path | Description | Files | SKILL.md lines | OpenAI metadata |',
    '| --- | --- | --- | ---: | ---: | --- |',
  ];
  skills.slice().sort(function byPath(a, b) {
    return a.relativePath.localeCompare(b.relativePath);
  }).forEach(function row(skill) {
    const metadata = fs.existsSync(path.join(skill.path, 'agents', 'openai.yaml')) ? 'yes' : 'no';
    lines.push(
      '| `' + skill.directoryName + '` | `' + skill.relativePath + '` | ' +
      tableText(skill.description || '(missing description)') + ' | ' +
      listSkillFiles(skill.path).length + ' | ' + skill.lineCount + ' | ' + metadata + ' |',
    );
  });
  lines.push('', 'Total: ' + skills.length + ' universal library skills.', '');
  return lines.join('\n');
}

function catalogIsCurrent(settings, selectedSkills) {
  if (!fs.existsSync(settings.catalogPath)) return false;
  return fs.readFileSync(settings.catalogPath, 'utf8') === generateCatalog(settings, selectedSkills);
}

function writeCatalog(settings, selectedSkills) {
  atomicWrite(settings.catalogPath, generateCatalog(settings, selectedSkills));
  return settings.catalogPath;
}

module.exports = {
  GENERATED_MARKER,
  catalogIsCurrent,
  generateCatalog,
  writeCatalog,
};
